version: 0.2

#env:
# variables:
#   JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
# parameter-store:
#   LOGIN_PASSWORD: "dockerLoginPassword"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y hugo
#     - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails 
#   pre_build:
#     commands:
#       - echo Entered the pre_build phase...
#       - docker login –u User –p $LOGIN_PASSWORD
#     finally:
#       - echo This always runs even if the login command fails 
#   build:
#     commands:
#       - echo Entered the build phase...
#       - echo Build started on `date`
#       - mvn install
#     finally:
#       - echo This always runs even if the install command fails
#   post_build:
#     commands:
#       - echo Entered the post_build phase...
#       - echo Build completed on `date`
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
#   discard-paths: yes
# secondary-artifacts:
#   artifact1:
#     files:
#       - target/messageUtil-1.0.jar
#     discard-paths: yes
#   artifact2:
#     files:
#       - target/messageUtil-1.0.jar
#     discard-paths: yes
# cache:
#   paths:
#     - '/root/.m2/**/*'